config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  root :to => 'sessions#new'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  before_validation { email.downcase! }
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :login_required
  private
  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy ]

  # GET /blogs or /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1 or /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)
    if params[:back]
      render :new
    else
      if @blog.save
        redirect_to blogs_path, notice: "ささやきました！"
      else
        render :new
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    if params[:back]
      render :edit
    else
      if @blog.update(blog_params)
        redirect_to blogs_path, notice: "ささやきを編集しました！"
      else
        render :edit
      end
    end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path, notice: "ささやきを削除しました！"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :content)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id), success: 'ログインしました'  
    else
      flash[:notice] = 'ログインに失敗しました'
      render :new
    end
  end
  
  def destroy
    session.delete(:user_id)
    redirect_to new_session_path, success: 'ログアウトしました'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :show, :update, :destroy]
  skip_before_action :login_required, only: [:new, :create]
  before_action :ensure_current_user, only: [:edit, :update, :destroy]

  def new
    if params[:back]
      @user = User.new(user_params)
    else
      @user = User.new
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def ensure_current_user
    if current_user.id != @user.id
      redirect_to user_path(current_user.id), warning: "権限がありません"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.content %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @blog.content %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PairPro</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class='body_wrapper'>
      <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="#">pair_pro</a>
          </div>
          <% if logged_in? %>
            <ul class="nav navbar-nav">
              <li><%= link_to "投稿一覧", blogs_path %></li>
              <li><%= link_to "投稿", new_blog_path %></li>
              <li><%= link_to "プロフィール", user_path(current_user.id) %></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li>
                <%= link_to "Logout", session_path(current_user.id), class: 'links', method: :delete %>
              </li>
            </ul>
          <% else %>
              <ul class="nav navbar-nav navbar-right">
                <li>
                  <%= link_to "Login",new_session_path %>
                </li>
                <li>
                  <%= link_to 'SignUp', new_user_path %>
                </li>
              </ul>
          <% end %>
        </div>
      </nav>
      <div class="flash_message">
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "#{key} bg-success") %>
        <% end %>
      </div>
      <%= yield %>
      <footer>
        <div class='footer'>
          <p class='copyright'>©️フッダーです ^o^</p>
        </div>
      </footer>
    </div>
  </body>
</html>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Sign up</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: @user, local: true, url: users_path) do |f| %>
  <div class="table_wrapper slide_left">
    <table>
      <tbody>
        <tr>
          <td><%= f.label :"名前" %></td>
          <td><%= f.text_field :name %></td>
        </tr>
        <tr>
          <td><%= f.label :"メールアドレス" %></td>
          <td><%= f.email_field :email %></td>
        </tr>
        <tr>
          <td><%= f.label :"パスワード"%></td>
          <td><%= f.password_field :password %></td>
        </tr>
        <tr>
          <td><%= f.label :"パスワード確認用" %></td>
          <td><%= f.password_field :password_confirmation %></td>
        </tr>
      </tbody>
    </table>
    <div>
      <%= f.submit "入力内容確認", class: "btn btn-warning #{'side_margin' if @user.id?} #{'button_middle' if !@user.id?}" %>
      <% if @user.id? %>
        <%= link_to '戻る', user_path(@user.id), class: "btn btn-warning side_margin" %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/users/show.html.erb
<div class="main_wrapper">
  <div>
    <h3 class='page_title'>プロフィール</h3>
  </div>
  <div class='add_profile_layout'>
    <div class="table_wrapper slide_left">
      <table>
        <tbody>
          <tr>
            <td><p>名前:</p></td>
            <td><p><%= @user.name %></p></td>
          </tr>
          <tr>
            <td><p>メールアドレス:</p></td>
            <td><p><%= @user.email %></p></td>
          </tr>
          <tr>
            <td><p>パスワード : </p></td>
            <td><p>＊＊＊＊＊＊＊＊</p></td>
          </tr>
          <tr>
            <td><p>パスワード確認用 : </p></td>
            <td><p>＊＊＊＊＊＊＊＊</p></td>
          </tr>
        </tbody>
      </table>
      <div class='button_area'>
        <% if current_user.id == @user.id %>
          <%= link_to "戻る", new_user_path, class: "btn btn-warning side_margin" %>
          <%= link_to "編集", edit_user_path(@user.id), class: "btn btn-warning side_margin" %>
          <%= link_to '退会', user_path(@user.id), method: :delete, data: { confirm: '本当に退会しますか？'}, class: "btn btn-warning side_margin" %>
        <% end %>
      </div>
    </div>
  </div>
</div>